### ISSUE TITLE
use GenerateId in CreateTodo

### ISSUE THREAD

**Issue by BenNewman90** [fac-15/CC_toDoList#13]
Create to do should make the todo object, including generating the id number. It's not logical to build the object over two functions.

The return value of CreateTodo can then be passed into addTodo as the second argument. This will make addTodo a pure function.

https://github.com/fac-15/CC_toDoList/blob/c4c8d2319777c2da677616507e3322e4999d947a/logic.js#L33

**Comment by martinbagshaw** [comment]
this will be covered in my next commit
